kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-app-deployment
  namespace: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: mayurnagekar/react-app:5 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always
